# Generated by Django 5.0.1 on 2024-01-30 23:41

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_remove_player_user_player_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='username',
        ),
        migrations.AddField(
            model_name='player',
            name='userID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
