# Generated by Django 5.0.1 on 2024-01-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_remove_player_username_player_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='userID',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
