# Generated by Django 5.0.1 on 2024-01-30 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_dealer_hand_game_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='dealer_hand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_as_dealer', to='game.hand'),
        ),
    ]
