# Generated by Django 5.0.1 on 2024-01-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_game_dealer_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='cards',
            field=models.JSONField(default=list),
        ),
    ]
